# Generated by Django 3.2.2 on 2021-05-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDEA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('logo_url', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=10000)),
                ('is_public', models.BooleanField(default=False)),
                ('people_interested', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.idea')),
            ],
        ),
        migrations.CreateModel(
            name='INDUSTRY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('0', 'Advertising'), ('1', 'Aerospace'), ('2', 'Agriculture'), ('3', 'Air Transport'), ('4', 'Alcoholic Beverages'), ('5', 'Alternative Energy'), ('6', 'Architectural Services'), ('7', 'Automotive'), ('8', 'Banking'), ('9', 'Business Services'), ('10', 'Chemical Manufacturing'), ('11', 'Construction'), ('12', 'Credit Unions'), ('13', 'Cruise Ships'), ('14', 'Defense'), ('15', 'Dentists'), ('16', 'Drug Manufacturers'), ('17', 'Education'), ('18', 'Electric Utilities'), ('19', 'Eletronics Manufacturing'), ('20', 'Energy & Natural Resources'), ('21', 'Farming'), ('22', 'Finance'), ('23', 'Food & Beverages'), ('24', 'For-profit Education'), ('25', 'Funeral Services'), ('26', 'Gambling & Casinos'), ('27', 'Gas & Oil'), ('28', 'General Contractors'), ('29', 'Health Services'), ('30', 'Home Builders'), ('31', 'Hotels, Motels & Tourism'), ('32', 'Insurance'), ('33', 'Internet'), ('34', 'Liquor, Wine & Beer'), ('35', 'Logging'), ('36', 'Marijuana'), ('37', 'Marine Transport'), ('38', 'Meat processing & products'), ('39', 'Medical Supplies'), ('40', 'Music Production'), ('41', 'Non-profit Organization'), ('42', 'Nutritional Supplements'), ('43', 'Oil & Gas'), ('44', 'Payday Lenders'), ('45', 'Pharmaceutical Manufacturing'), ('46', 'Power Utilities'), ('47', 'Printing & Publishing'), ('48', 'Radio/TV Stations'), ('49', 'Real Estate'), ('50', 'Record Label'), ('51', 'Recreation'), ('52', 'Restuarants'), ('53', 'Retail Sales'), ('54', 'Savings & Loans'), ('55', 'Schools/Education'), ('56', 'Securities & Investments'), ('57', 'Teachers Unions'), ('58', 'Telecom Services'), ('59', 'Tobacco'), ('60', 'Transportation'), ('61', 'Trucking'), ('62', 'TV Production'), ('63', 'Venture Capital'), ('64', 'Other')], default=('64', 'Other'), max_length=70)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.idea')),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80)),
                ('auth_level', models.IntegerField()),
                ('function', models.CharField(max_length=250)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.idea')),
            ],
        ),
    ]
