# Generated by Django 3.2.2 on 2021-05-06 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210506_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
