# Generated by Django 3.2.2 on 2021-05-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_idea_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='logo_url',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/ProhibitionSign2.svg/1200px-ProhibitionSign2.svg.png', max_length=300),
        ),
    ]
