# Generated by Django 3.2.2 on 2021-05-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_idea_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='people_interested',
        ),
        migrations.CreateModel(
            name='PeopleInterested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.idea')),
            ],
        ),
    ]
