# Generated by Django 3.2.2 on 2021-05-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_peopleinterested_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinterested',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
