# Generated by Django 3.2.2 on 2021-05-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_peopleinterested_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='people_interested',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PeopleInterested',
        ),
    ]
