# Generated by Django 3.2.2 on 2021-05-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
