# Generated by Django 3.2.2 on 2021-05-13 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000000),
            preserve_default=False,
        ),
    ]
