# Generated by Django 3.2.2 on 2021-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
